/**
 * Mini App profile lookup.
 *
 * The Telegram registration bot (scripts/telegram-bot.mjs) upserts every user
 * who shares their phone via the bot's «ስልክ አጋራ» button into public.profiles:
 *
 *   id           — UUID primary key (generated by Supabase, never written by us)
 *   telegram_id  — the Telegram user id as BIGINT (unique)
 *   first_name / last_name / username — from Telegram
 *   phone_number — the shared phone number
 *
 * The Mini App (anon-key client) reads this row to display the user's
 * registered identity on the Profile tab and to attach the phone number /
 * telegram id to every ticket purchase transaction (payments + tickets).
 */
import { supabase } from '@/lib/supabase/client';
import type { TelegramUser } from '@/lib/tma';
import { toDbUserId } from '@/lib/user-identity';

export type UserProfile = {
  id: string;
  telegram_id: string | number;
  first_name: string | null;
  last_name: string | null;
  username: string | null;
  phone_number: string | null;
  photo_url: string | null;
};

/**
 * Fetch the profile row for a Telegram Mini App user by their telegram_id.
 *
 * Returns `null` when there is no Telegram user (browser/guest session), the
 * id is not a real Telegram id (guest ids are negative), or no profile has
 * been registered yet. Never throws — checkout and the profile UI treat a
 * null result as "not registered".
 */
export async function fetchUserProfile(
  telegramUser: TelegramUser | null,
): Promise<UserProfile | null> {
  if (!telegramUser || telegramUser.id === undefined || telegramUser.id === null) {
    return null;
  }

  // Canonical numeric string (see lib/user-identity.ts). Guest ids are
  // negative and can never match a bot-registered profile — skip the query.
  const telegramId = toDbUserId(telegramUser.id);
  if (!telegramId || telegramId.startsWith('-')) return null;

  try {
    // telegram_id is BIGINT in the live schema; the numeric string casts
    // cleanly, and a text-typed drift column also matches (PostgREST casts).
    const { data, error } = await supabase
      .from('profiles')
      .select('id, telegram_id, first_name, last_name, username, phone_number, photo_url')
      .eq('telegram_id', telegramId.includes('.') ? telegramId : Number(telegramId))
      .maybeSingle();

    if (error) {
      console.warn('fetchUserProfile: profiles lookup failed:', error.message);
      return null;
    }
    return (data as UserProfile | null) ?? null;
  } catch (err) {
    console.warn('fetchUserProfile threw (non-fatal):', err);
    return null;
  }
}

/**
 * Persist the Mini App avatar (initDataUnsafe.user.photo_url) onto the
 * bot-registered profile row so the identity survives outside the TMA
 * context. Non-fatal by design:
 *   • the anon UPDATE policy (migration 023) restricts writes to the
 *     photo_url / updated_at columns only,
 *   • when the profile row does not exist yet (phone never shared) the
 *     insert path is RLS-blocked and this simply returns false.
 */
export async function saveProfilePhoto(
  telegramUser: TelegramUser | null,
  photoUrl: string,
): Promise<boolean> {
  if (!telegramUser || telegramUser.id === undefined || telegramUser.id === null) {
    return false;
  }
  const telegramId = toDbUserId(telegramUser.id);
  if (!telegramId || telegramId.startsWith('-')) return false;

  try {
    const { error } = await supabase
      .from('profiles')
      .upsert(
        {
          telegram_id: Number(telegramId),
          photo_url: photoUrl,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'telegram_id' },
      );
    if (error) {
      console.warn('saveProfilePhoto: profiles upsert failed:', error.message);
      return false;
    }
    return true;
  } catch (err) {
    console.warn('saveProfilePhoto threw (non-fatal):', err);
    return false;
  }
}
