-- 023_profiles_table.sql
-- Telegram-bot registration target table.
--
-- scripts/telegram-bot.mjs upserts every user who shares their contact via the
-- bot's /start reply keyboard ("📱 ስልክ አጋራ") into public.profiles:
--
--   id           — UUID primary key GENERATED BY SUPABASE (gen_random_uuid()).
--                  The bot never writes this column — sending a Telegram id as
--                  `id` fails with 22P02 "invalid input syntax for type uuid".
--   telegram_id  — the Telegram user id as BIGINT (UNIQUE — the bot upserts
--                  with onConflict: "telegram_id" so re-sharing the contact
--                  refreshes the row instead of duplicating it).
--   first_name   — from Telegram (message.from.first_name).
--   last_name    — from Telegram (message.from.last_name), when present.
--   username     — from Telegram (message.from.username), when present.
--   phone_number — the shared contact (message.contact.phone_number).
--
-- The bot writes with the SERVICE-ROLE key, which bypasses RLS, so no write
-- policy is required. Idempotent — safe to re-run.

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  telegram_id bigint unique,
  first_name text,
  last_name text,
  username text,
  phone_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Guarantee the UNIQUE constraint used by the bot's upsert
-- (onConflict: "telegram_id") even if the table pre-dates this migration.
create unique index if not exists profiles_telegram_id_key on public.profiles (telegram_id);

-- Fast lookups by phone / username (admin broadcasts, dedupe checks).
create index if not exists profiles_phone_number_idx on public.profiles (phone_number);
create index if not exists profiles_username_idx    on public.profiles (username);

-- Avatar (item: Mini App Profile photo). The Telegram WebApp provides
-- initDataUnsafe.user.photo_url; the profile card renders it live and syncs
-- it here so the avatar survives outside the TMA context. The registration
-- bot never writes this column (its payload omits it), so re-sharing the
-- phone never clobbers a saved avatar.
alter table public.profiles add column if not exists photo_url text;

alter table public.profiles enable row level security;

-- Profiles are personal data. The bot (service-role key) writes rows, and the
-- Mini App (anon-key client — Telegram Mini App users have NO Supabase auth
-- session) must be able to READ the profile by telegram_id to display the
-- registered identity on the Profile tab and to attach the phone number to
-- ticket purchases. This matches the app's permissive read posture on
-- payments/tickets. Writes remain service-role only (no insert/update policy).
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

-- Avatar sync: the Mini App (anon key) may refresh a profile's photo_url —
-- and NOTHING else. RLS gates the row; a column-level GRANT restricts the
-- writable columns even if a future policy is widened. The bot's own writes
-- (service-role key) bypass RLS and are unaffected.
drop policy if exists "profiles_update_photo" on public.profiles;
create policy "profiles_update_photo"
  on public.profiles for update
  using (true)
  with check (true);
revoke update on table public.profiles from anon;
grant update (photo_url, updated_at) on public.profiles to anon;